var json_LIBERTAD_CAPACHOVIEJOMunicipio_Capacho_Viejo_Parroquia_LibertadLibertad_Oronimia_7 = {
"type": "FeatureCollection",
"name": "LIBERTAD_CAPACHOVIEJOMunicipio_Capacho_Viejo_Parroquia_LibertadLibertad_Oronimia_7",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "pk": "1", "id": "1", "código": "201503", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "3", "parroquia": "Manuel Felipe Rúgeles", "capital_pa": "El Pueblito", "nombre": "Cerro la Estilosa", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.308362282617608, 7.802035744249932 ] ] } },
{ "type": "Feature", "properties": { "pk": "2", "id": "2", "código": "201501", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "1", "parroquia": "Libertad", "capital_pa": "Capacho Viejo", "nombre": "Pico La Muera", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.333016263888609, 7.792688284819049 ] ] } },
{ "type": "Feature", "properties": { "pk": "3", "id": "3", "código": "201501", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "1", "parroquia": "Libertad", "capital_pa": "Capacho Viejo", "nombre": "Páramo Salado Negro", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.350188186749435, 7.805557055906926 ] ] } },
{ "type": "Feature", "properties": { "pk": "4", "id": "4", "código": "201501", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "15", "municipio": "Capacho Viejo", "capital_mu": "Capacho Viejo", "código_par": "1", "parroquia": "Libertad", "capital_pa": "Capacho Viejo", "nombre": "Fila Barro Amarillo", "fuente": "Digitalizado a partir de las Cartas Topográficas 1:25000 y 1:100000. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.337574596482384, 7.775783736796507 ] ] } }
]
}
